### ISSUE TITLE
Roadmap 0.02 - Some Basic Syntax

### ISSUE THREAD

**Issue by PeyTy** [PeyTy/Hexa#4]
- [x] `//`
- [x] `/* */`
- [x] `/* /* */ */`
- [x] `/** doc **/`
- [x] Int
- [x] Float
- [x] true false
- [x] Underscore
- [x] break continue throw this null ternary if else while etc
- [x] 1-byte ops lexe `[ ] ( ) { } ; : * ^` etc
- [x] 2-byte ops lexe `++ -- <<` etc
- [x] 3-byte ops lexe `... >>>`

- [x] unop parse
- [x] binop parse
- [x] binop predecence

- [x] Gen dump
- [x] Gen js

**Comment by PeyTy** [comment]
Its review&push time!
