### ISSUE TITLE
Roadmap 0.03 - Adding Types

### ISSUE THREAD

**Issue by PeyTy** [PeyTy/Hexa#5]
Parsing:
- [ ] Type def parsing
- [ ] new
- [ ] var
- [ ] let
- [ ] function
- [ ] Arrow function
- [ ] super
- [ ] `{ obj }`
- [ ] `[ array ]`
- [ ] field.access
- [ ] array.access
- [ ] assign ops
- [ ] casting
- [ ] reg

Checking locals:
- [ ] Lexical var/let/etc scope
- [ ] var/let/return/throw/etc arent expressions, they are statements
- [ ] Apply types
- [ ] Infer types from assigments
- [ ] Type reference expr

Gen:
- [ ] Gen dump
- [ ] Gen js
